# Generated by Django 5.2.1 on 2025-06-16 08:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_otp_verified_at_user_otp_verified_for_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_code',
            field=models.CharField(default=core.models.generate_friend_code, editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
